stages:
  - release

release:
  stage: release
  image: oven/bun:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - when: never
  before_script:
    - apt-get update -qq && apt-get install -y -qq git ca-certificates
    - git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/flying-dice/abtree.git"
    - git config --global user.email "semantic-release@abtree"
    - git config --global user.name "semantic-release"
    - bun install
  script:
    - bunx semantic-release
