/**
 * Dump the OpenAPI schema generated by the Hono app to stdout or a
 * file. Used by `bun run orval` so the client regenerates without
 * starting a real HTTP server.
 *
 * The runtime resolves `EXECUTIONS_DIR` from env at import time. The
 * schema dump doesn't read any executions, so a synthetic path keeps
 * the imports happy.
 */
import { writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

process.env.ABTREE_EXECUTIONS_DIR ??= join(tmpdir(), "abtree-schema-dummy");
process.env.ABTREE_SNAPSHOTS_DIR ??= join(tmpdir(), "abtree-schema-dummy-snapshots");

const { app } = await import("../src/server/app.ts");
const { Application } = await import("../src/server/Application.ts");
const { setApplication } = await import("../src/server/ApplicationFactory.ts");

setApplication(
	new Application({ executionsPath: process.env.ABTREE_EXECUTIONS_DIR }),
);

const req = new Request("http://localhost/v3/api-docs");
const res = await app.fetch(req);
if (!res.ok) {
	console.error(`Schema dump failed: ${res.status} ${res.statusText}`);
	process.exit(1);
}

const schema = await res.text();
const outFile = process.argv[2];
if (outFile) {
	writeFileSync(outFile, schema, "utf-8");
	console.error(`OpenAPI schema → ${outFile}`);
} else {
	process.stdout.write(schema);
}
