/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * @abtree/serve
 * Development documentation
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import { customFetch } from './fetcher';
export interface ExecutionSummary {
  id: string;
  tree: string;
  summary: string;
  status: string;
  phase: string;
  cursor: string;
  snapshot: string;
  protocolAccepted: boolean;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  traceCount: number;
  createdAt: string;
  updatedAt: string;
}

export type TraceEntryKind = typeof TraceEntryKind[keyof typeof TraceEntryKind];


export const TraceEntryKind = {
  evaluate: 'evaluate',
  instruct: 'instruct',
  protocol: 'protocol',
} as const;

export interface TraceEntry {
  ts: string;
  kind: TraceEntryKind;
  cursor: string;
  name: string;
  submitted: string;
  outcome: string;
  note?: string;
}

export type ExecutionLocal = {[key: string]: unknown};

export type ExecutionGlobal = {[key: string]: unknown};

export type ExecutionRuntimeNodeStatus = {[key: string]: 'success' | 'failure' | 'running'};

export type ExecutionRuntimeStepIndex = {[key: string]: number};

export type ExecutionRuntimeRetryCount = {[key: string]: number};

export type ExecutionRuntime = {
  nodeStatus: ExecutionRuntimeNodeStatus;
  stepIndex: ExecutionRuntimeStepIndex;
  retryCount: ExecutionRuntimeRetryCount;
};

export interface Execution {
  id: string;
  tree: string;
  summary: string;
  status: string;
  phase: string;
  cursor: string;
  snapshot: string;
  protocolAccepted: boolean;
  trace: TraceEntry[];
  local: ExecutionLocal;
  global: ExecutionGlobal;
  runtime: ExecutionRuntime;
  createdAt: string;
  updatedAt: string;
}

export type ErrorDataStatus = typeof ErrorDataStatus[keyof typeof ErrorDataStatus];


export const ErrorDataStatus = {
  NUMBER_100: 100,
  NUMBER_101: 101,
  NUMBER_102: 102,
  NUMBER_103: 103,
  NUMBER_200: 200,
  NUMBER_201: 201,
  NUMBER_202: 202,
  NUMBER_203: 203,
  NUMBER_204: 204,
  NUMBER_205: 205,
  NUMBER_206: 206,
  NUMBER_207: 207,
  NUMBER_300: 300,
  NUMBER_301: 301,
  NUMBER_302: 302,
  NUMBER_303: 303,
  NUMBER_304: 304,
  NUMBER_305: 305,
  NUMBER_307: 307,
  NUMBER_308: 308,
  NUMBER_400: 400,
  NUMBER_401: 401,
  NUMBER_402: 402,
  NUMBER_403: 403,
  NUMBER_404: 404,
  NUMBER_405: 405,
  NUMBER_406: 406,
  NUMBER_407: 407,
  NUMBER_408: 408,
  NUMBER_409: 409,
  NUMBER_410: 410,
  NUMBER_411: 411,
  NUMBER_412: 412,
  NUMBER_413: 413,
  NUMBER_414: 414,
  NUMBER_415: 415,
  NUMBER_416: 416,
  NUMBER_417: 417,
  NUMBER_418: 418,
  NUMBER_419: 419,
  NUMBER_420: 420,
  NUMBER_421: 421,
  NUMBER_422: 422,
  NUMBER_423: 423,
  NUMBER_424: 424,
  NUMBER_426: 426,
  NUMBER_428: 428,
  NUMBER_429: 429,
  NUMBER_431: 431,
  NUMBER_451: 451,
  NUMBER_500: 500,
  NUMBER_501: 501,
  NUMBER_502: 502,
  NUMBER_503: 503,
  NUMBER_504: 504,
  NUMBER_505: 505,
  NUMBER_507: 507,
  NUMBER_511: 511,
} as const;

export interface ErrorData {
  timestamp: string;
  status: ErrorDataStatus;
  error: string;
  message: string;
}

export type TreeNodeDataKind = typeof TreeNodeDataKind[keyof typeof TreeNodeDataKind];


export const TreeNodeDataKind = {
  action: 'action',
  sequence: 'sequence',
  selector: 'selector',
  parallel: 'parallel',
  ref: 'ref',
} as const;

export type TreeNodeDataStepsItemKind = typeof TreeNodeDataStepsItemKind[keyof typeof TreeNodeDataStepsItemKind];


export const TreeNodeDataStepsItemKind = {
  evaluate: 'evaluate',
  instruct: 'instruct',
} as const;

export type TreeNodeDataStepsItem = {
  kind: TreeNodeDataStepsItemKind;
  text: string;
};

export interface TreeNodeData {
  id: string;
  path: string;
  name: string;
  kind: TreeNodeDataKind;
  ref: string | null;
  steps?: TreeNodeDataStepsItem[];
  status: 'success' | 'failure' | 'running' | null;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  retries?: number;
  x: number;
  y: number;
}

export interface TreeEdgeData {
  id: string;
  source: string;
  target: string;
}

export interface TreeGraph {
  nodes: TreeNodeData[];
  edges: TreeEdgeData[];
  width: number;
  height: number;
}

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


  type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getExecutionsResponse200 = {
  data: ExecutionSummary[]
  status: 200
}

export type getExecutionsResponseSuccess = (getExecutionsResponse200) & {
  headers: Headers;
};
;

export type getExecutionsResponse = (getExecutionsResponseSuccess)

export const getGetExecutionsUrl = () => {




  return `/api/executions`
}

/**
 * @summary List executions
 */
export const getExecutions = async ( options?: RequestInit): Promise<getExecutionsResponse> => {

  return customFetch<getExecutionsResponse>(getGetExecutionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetExecutionsKey = () => [`/api/executions`] as const;

export type GetExecutionsQueryResult = NonNullable<Awaited<ReturnType<typeof getExecutions>>>

/**
 * @summary List executions
 */
export const useGetExecutions = <TError = unknown>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getExecutions>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customFetch> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetExecutionsKey() : null);
  const swrFn = () => getExecutions(requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getExecutionResponse200 = {
  data: Execution
  status: 200
}

export type getExecutionResponse404 = {
  data: ErrorData
  status: 404
}

export type getExecutionResponseSuccess = (getExecutionResponse200) & {
  headers: Headers;
};
export type getExecutionResponseError = (getExecutionResponse404) & {
  headers: Headers;
};

export type getExecutionResponse = (getExecutionResponseSuccess | getExecutionResponseError)

export const getGetExecutionUrl = (id: string,) => {




  return `/api/executions/${id}`
}

/**
 * @summary Get a single execution
 */
export const getExecution = async (id: string, options?: RequestInit): Promise<getExecutionResponse> => {

  return customFetch<getExecutionResponse>(getGetExecutionUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetExecutionKey = (id: string,) => [`/api/executions/${id}`] as const;

export type GetExecutionQueryResult = NonNullable<Awaited<ReturnType<typeof getExecution>>>

/**
 * @summary Get a single execution
 */
export const useGetExecution = <TError = ErrorData>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getExecution>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customFetch> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetExecutionKey(id) : null);
  const swrFn = () => getExecution(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

export type getExecutionTreeResponse200 = {
  data: TreeGraph
  status: 200
}

export type getExecutionTreeResponse404 = {
  data: ErrorData
  status: 404
}

export type getExecutionTreeResponseSuccess = (getExecutionTreeResponse200) & {
  headers: Headers;
};
export type getExecutionTreeResponseError = (getExecutionTreeResponse404) & {
  headers: Headers;
};

export type getExecutionTreeResponse = (getExecutionTreeResponseSuccess | getExecutionTreeResponseError)

export const getGetExecutionTreeUrl = (id: string,) => {




  return `/api/executions/${id}/tree`
}

/**
 * @summary ReactFlow graph for an execution's tree snapshot
 */
export const getExecutionTree = async (id: string, options?: RequestInit): Promise<getExecutionTreeResponse> => {

  return customFetch<getExecutionTreeResponse>(getGetExecutionTreeUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetExecutionTreeKey = (id: string,) => [`/api/executions/${id}/tree`] as const;

export type GetExecutionTreeQueryResult = NonNullable<Awaited<ReturnType<typeof getExecutionTree>>>

/**
 * @summary ReactFlow graph for an execution's tree snapshot
 */
export const useGetExecutionTree = <TError = ErrorData>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getExecutionTree>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customFetch> }
) => {
  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetExecutionTreeKey(id) : null);
  const swrFn = () => getExecutionTree(id, requestOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
