---
title: "iter demo (complete)"
---
flowchart TD
    Reach_Threshold{{"Reach Threshold\n[selector]"}}
    0_Pass{{"Pass\n[sequence]"}}
    Reach_Threshold --> 0_Pass
    style 0_Pass fill:#f87171,stroke:#dc2626,color:#450a0a
    0_0_Increment["Increment\n[action]"]
    0_Pass --> 0_0_Increment
    style 0_0_Increment fill:#4ade80,stroke:#16a34a,color:#052e16
    0_0_Test["Test\n[action]"]
    0_Pass --> 0_0_Test
    style 0_0_Test fill:#f87171,stroke:#dc2626,color:#450a0a
    0_Pass{{"Pass\n[sequence]"}}
    Reach_Threshold --> 0_Pass
    style 0_Pass fill:#f87171,stroke:#dc2626,color:#450a0a
    0_1_Increment["Increment\n[action]"]
    0_Pass --> 0_1_Increment
    style 0_1_Increment fill:#4ade80,stroke:#16a34a,color:#052e16
    0_1_Test["Test\n[action]"]
    0_Pass --> 0_1_Test
    style 0_1_Test fill:#f87171,stroke:#dc2626,color:#450a0a
    0_Pass{{"Pass\n[sequence]"}}
    Reach_Threshold --> 0_Pass
    style 0_Pass fill:#f87171,stroke:#dc2626,color:#450a0a
    0_2_Increment["Increment\n[action]"]
    0_Pass --> 0_2_Increment
    style 0_2_Increment fill:#4ade80,stroke:#16a34a,color:#052e16
    0_2_Test["Test\n[action]"]
    0_Pass --> 0_2_Test
    style 0_2_Test fill:#f87171,stroke:#dc2626,color:#450a0a
    0_Pass{{"Pass\n[sequence]"}}
    Reach_Threshold --> 0_Pass
    style 0_Pass fill:#4ade80,stroke:#16a34a,color:#052e16
    0_3_Increment["Increment\n[action]"]
    0_Pass --> 0_3_Increment
    style 0_3_Increment fill:#4ade80,stroke:#16a34a,color:#052e16
    0_3_Test["Test\n[action]"]
    0_Pass --> 0_3_Test
    style 0_3_Test fill:#4ade80,stroke:#16a34a,color:#052e16
