---
title: "ref demo (complete)"
---
flowchart TD
    Counter_Demo{{"Counter Demo\n[sequence]"}}
    0_Test{{"Test\n[selector]"}}
    Counter_Demo --> 0_Test
    style 0_Test fill:#4ade80,stroke:#16a34a,color:#052e16
    0_0_Check_Counter["Check Counter\n[action]"]
    0_Test --> 0_0_Check_Counter
    style 0_0_Check_Counter fill:#f87171,stroke:#dc2626,color:#450a0a
    0_0_Increment["Increment\n[action]"]
    0_Test --> 0_0_Increment
    style 0_0_Increment fill:#4ade80,stroke:#16a34a,color:#052e16
