---
title: "retry demo (complete)"
---
flowchart TD
    Reach_Threshold{{"Reach Threshold\n[sequence]"}}
    0_Pass{{"Pass\n[sequence]"}}
    Reach_Threshold --> 0_Pass
    style 0_Pass fill:#4ade80,stroke:#16a34a,color:#052e16
    0_0_Increment["Increment\n[action]"]
    0_Pass --> 0_0_Increment
    style 0_0_Increment fill:#4ade80,stroke:#16a34a,color:#052e16
    0_0_Test["Test\n[action]"]
    0_Pass --> 0_0_Test
    style 0_0_Test fill:#4ade80,stroke:#16a34a,color:#052e16
